version: 2
project_name: gopanix
release:
  github:
    owner: mickamy
    name: gopanix
  draft: false
  prerelease: "false"

builds:
  - id: gopanix
    main: ./cmd/gopanix/main.go
    goos: [ darwin, linux, windows ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - "-X github.com/mickamy/gopanix/internal/cli/version/version.version={{.Version}}"
    binary: gopanix

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
